### ISSUE TITLE
Login Webview crash on Linux

### ISSUE THREAD

**Issue by herve-er** [Infomaniak/desktop-kDrive#307]
> Dear Infomaniak team,
> 
> after starting the 3.5.8 AppImage I get the following Popup:
> 
> Everytime I close it it pops up again immediately and blocks the
> initialization of the login process. 
> 
> Same happens with version 3.6.1 AppImage
> 
> and version 3.6.4 (Linux Mint 21.3 Cinnamon).
> 
> Can you please check this issue.
> 
> Thanks in advance.
> Harald
>

**Comment by herve-er** [comment]
[20240917_2059_kDrive (1).log](https://github.com/user-attachments/files/17058833/20240917_2059_kDrive.1.log)
[20240917_2057_kDrive (1).log.gz](https://github.com/user-attachments/files/17058835/20240917_2057_kDrive.1.log.gz)

![368558071-3c0979b2-ee58-41a0-9b23-a941beefa4d2](https://github.com/user-attachments/assets/9fb54470-445e-4adb-9dfc-7fa263211af6)

**Comment by herve-er** [comment]
Hi @harryburli,

It appears that the issue arises from the opening of the login webview. 
This often occurs due to the following reasons:
1. The operating system (OS) is not up to date. Can you try to execute the following commands:
1.1 sudo apt-get update 
1.2 sudo apt-get upgrade
2. Also ensure that your graphics card driver is up to date, preferably by downloading it directly from your graphics card manufacturer's website (e.g., Nvidia: https://www.nvidia.com/en-us/drivers/).

This should resolve the issue. If not, could you also provide us with the client log (yyyymmdd_hhmm_kDrive-client.log)?

**Comment by harryburli** [comment]
[20240912_1605_kDrive.log](https://github.com/user-attachments/files/17131427/20240912_1605_kDrive.log)
[20240925_1501_kDrive_client.log.](https://github.com/user-attachments/files/17131478/20240925_1501_kDrive_client.log)

The System is up to date also the newest Nvidia Driver is installed but it does  still not work.

**Comment by herve-er** [comment]
Hello @harryburli, 
It appears that we are encountering an issue where certain AppArmor restriction increases are preventing us from displaying the login window on some Linux distributions. This could explain why you the pop still pops up.

Could you try the following workaround found in another issue: https://github.com/Infomaniak/desktop-kDrive/issues/237#issuecomment-2373739792

Edit the file /etc/apparmor.d/kdrive with the the following content:

```
# This profile allows everything and only exists to give the
# application a name instead of having the label "unconfined"

abi <abi/4.0>,
include <tunables/global>

profile kdrive <path_to_kDrive_appimage> flags=(unconfined) {
  userns,
  
  # Site-specific additions and overrides. See local/README for details.
  include if exists <local/kdrive>
}
```
Restarted apparmor with `sudo service apparmor restart`

**Comment by harryburli** [comment]
Hi, my computer is currently being repaired because it is defective. I can only test it once it is back. :-(

**Comment by harryburli** [comment]
Hi, tested it but it did not work.
Still the exact same issue.

**Comment by herve-er** [comment]
Hi @harryburli,

First, I apologize for the delay in response.

From your log, it seems that you're still on version 3.6.4 of kDrive. Could you please update to the latest version, as it includes some changes in login behavior (https://github.com/Infomaniak/desktop-kDrive/pull/280)?

Once updated, if the issue persists, could you open kDrive, wait for the popup to appear, close it, let it appear again, and then send us the kDrive and kDrive_client logs?

Thank you.
